### ISSUE TITLE
Change warning of bundling/merging if request protocol is HTTP/2

### ISSUE THREAD

**Issue by JeroenVanLeusden** [magehost/performance-dashboard#4]
We should check if request protocol is HTTP/2 and if so, set the status of merging and bundling css/js to "OK" even though they're disabled.

For more information click [here](https://www.byte.nl/blog/gebruik-je-magento-en-http2-zet-jscss-merging-uit).

**Comment by jeroenvermeulen** [comment]
@JeroenVanLeusden Thank you, you are right. I will change it.
In Magento 2.2 the config setting has disappeared in `production` mode so there we don't show the check.

**Comment by hostep** [comment]
Please try to make this decision based on actual proof, not on some theoretical basis. It would be great if someone could actually benchmark to see if this is true or not.
I think it might be true for css files, but not for javascript files in Magento2.

I personally haven't seen any super big performance gains when using HTTP/2 because all the small js files are loaded through requirejs when not bundled/merged and that doesn't seem to benefit from HTTP/2 a lot.
But that was almost a year ago, maybe things have changed in the mean time ...

It might get better once this is integrated in Magento2 I think: https://github.com/antonkril/magento-rjs-config

Please don't assume that what I tell here is true, nothing of the above is based on scientific evidence :)

**Comment by jeroenvermeulen** [comment]
Fixed in v1.13.0
